### PR TITLE
Sponsors redesign

### PR DESCRIPTION
**Pull request by elliottwilliams**
I'm keeping track of the work necessary to redesign the sponsors widget here. Will merge when completed.
- [x] Create a list (in yaml) of sponsors, so that the sponsor list can be modified without touching template code.
- [x] Lay out the sponsor images with flexbox, [in a flexible grid](https://cloud.githubusercontent.com/assets/910198/16066818/8c000f02-3284-11e6-8f54-74423b4558e3.png)
- [x] Ensure that sponsor images are scaled down on mobile
- [x] Remove Cook (they are no longer a sponsor)
- [ ] Add sponsor URLs
- [x] Get a sign off from Mikel and/or Amanda

### CODE REVIEW

**Comment by elliottwilliams** [comment]
@mikelberger do you have higher-res versions of the sponsor logos? Everything in the repository is 50px  high, so sponsors with narrow logos are very small compared to those with wide logos. (smallest is 38x50, largest 493x50)

**Comment by elliottwilliams** [comment]
Here's what I've got so far. Look good?

screen shot 2016-07-08 at 20 19 23

screen shot 2016-07-08 at 20 20 06

**Comment by elliottwilliams** [comment]
Waiting on @amandafindlay / Emma to get URLs for the sponsors. Once I have sponsor urls, I'll update the `sponsors.yaml` file and change the sponsors template to link each logo to the respective sponsor's website.

**Comment by mikelberger** [comment]
@elliottwilliams this looks good. But if you now or in the future need higher res logos, @amandafindlay probably has them or can get them. But I wouldn't worry about it now.

**Comment by elliottwilliams** [comment]
Sponsor urls received from Amy:

[sponsor_urls.csv.txt](https://github.com/matchboxcowork/matchboxstudio.org/files/369963/sponsor_urls.csv.txt)

**Comment by elliottwilliams** [comment]
Alright, I've added sponsor links to each sponsor (thanks Amy!) and am ready to push these changes to the site.

Here's how it looks at iPhone 6 screen size. I added the same orange underline we use on text links to indicate that the sponsor logos are linked:

screen shot 2016-07-19 at 16 24 40

**Pull request merged**
