### PR TITLE
Video hero (closes #14)

### LINKED ISSUE #14: Hero unit redesign
Per today's design meeting, we are redesigning the main hero unit:
- The intro video will be replaced by an [autoplaying background video](https://vimeo.com/95767157), the MBX logo, and ghost buttons to learn more and apply.
  - Buttons: "Look Around" and "Apply for Membership"
- The video should be overlayed with a black pixel grid, to darken the video and emphasize the logo and CTA
- I was given a set of vector MBX logos, we should render one for the logo here.

Whiteboard mockup:

mbx_hero

This new design differs from and closes #11.

### PR DESCRIPTION
**Pull request by elliottwilliams**
Here's my work on the redesigned hero unit. I'll try to get it up on the web so you guys can play with it, but here's a screenshot of its current behavior.

screen shot 2016-11-23 at 10 33 41

I also reimplemented the way the membership application is opened, so once this is merged, we can direct-link to the application from http://matchboxstudio.org/#app (closing #15).

### CODE REVIEW

**Comment by elliottwilliams** [comment]
Here's a version of the site with the video hero: http://104.131.179.41

@mikelberger @amandafindlay let me know how things look!

**Comment by mikelberger** [comment]
Thanks, @elliottwilliams. I reviewed with Jason and we think it looks good. Jason's only feedback was that the buttons are a little heavy. Maybe a little smaller, thinner outlines, and lighter text.

So if its easy to try out something in that end, go ahead. But it's not crucial. I'm fine with shipping it as is.

When you're done with that, please get with @jhewitt12 and work out how to merge your stuff in with his so we can hopefully do a push here soon.

Is there anything else on your todo list? I think @jhewitt12 had the rest of the issues on his. Do you have time to work on anything else in the near term (next two weeks)? I'm fine with having @jhewitt12 finish up his items and then we can all regroup after the updates are live.

Thanks!

**Comment by elliottwilliams** [comment]
Updated demo at http://104.131.179.41

Here's the lightened buttons: 
screen shot 2016-12-02 at 17 01 18

**Comment by mikelberger** [comment]
Sorry for the delay in getting back on this. Jason changed the wording on the buttons and added a line of text. His thinking: "I feel like it needs a line of text or something so the buttons don’t look like they’re just floating too bad"

screen shot 2016-12-07 at 12 02 40 pm

Here is the font it is in. https://www.dropbox.com/s/h8hnxfnsknv5zfy/ThirstyRoughBlackOne%20copy.otf?dl=0

My thought is have the text start to wrap at narrower sizes, but as it gets too narrow just have it disappear. It will looks weird if most of the words are just vertically stacked.

Thoughts on those changes?

**Comment by elliottwilliams** [comment]
I like that. I'll get it coded up and let you look over it.

**Comment by jhewitt12** [comment]
The font can go smaller on small screens too. I could make a media query
that says make it this font-size on small devices. Then the words wouldn't
be stacked. But if the text isn't that important than maybe making it
disappear is a better option.

**Comment by jhewitt12** [comment]
Whoops. Thought you were talking to me Mikel.

**Comment by elliottwilliams** [comment]
Take a look at this: https://morning-stream-47470.herokuapp.com

I like it, although I think the new button titles are a little vague. What would you think of "Explore" and "Apply to Join" or "Join us"? 

Here it is in a handful of size classes:
localhost-9292- 1
localhost-9292-
localhost-9292- ipad 1
localhost-9292- ipad
localhost-9292- iphone 6 1
localhost-9292- iphone 6

**Comment by mikelberger** [comment]
Looks good. Leave the button text as is. It is a little vague but in this case I think that's ok. The simplicity is worth it.

Let's coordinate with Josh and see if we can get a set of stuff released soon.

-Mikel
765-490-6321

**Pull request merged**
